"""add mandatory exit criteria fields to poc_tracker

Revision ID: 6d4dfe68c4fb
Revises: 128d06af2ba3
Create Date: 2026-08-03 10:52:37.567257

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6d4dfe68c4fb'
down_revision: Union[str, Sequence[str], None] = '128d06af2ba3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('poc',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('opportunity_id', sa.Integer(), nullable=False),
    sa.Column('objective', sa.Text(), nullable=False),
    sa.Column('success_metric', sa.Text(), nullable=False),
    sa.Column('target_date', sa.Date(), nullable=False),
    sa.Column('failure_condition', sa.Text(), nullable=False),
    sa.Column('stakeholder_signoff', sa.Boolean(), nullable=False),
    sa.Column('outcome', sa.String(length=20), nullable=True),
    sa.Column('outcome_notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('poc_tracker', sa.Column('objective', sa.Text(), nullable=False))
    op.add_column('poc_tracker', sa.Column('success_metric', sa.Text(), nullable=False))
    op.add_column('poc_tracker', sa.Column('target_date', sa.Date(), nullable=False))
    op.add_column('poc_tracker', sa.Column('failure_condition', sa.Text(), nullable=False))
    op.add_column('poc_tracker', sa.Column('stakeholder_signoff', sa.Boolean(), nullable=False))
    op.add_column('poc_tracker', sa.Column('outcome', sa.String(length=20), nullable=True))
    op.add_column('poc_tracker', sa.Column('outcome_notes', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('poc_tracker', 'outcome_notes')
    op.drop_column('poc_tracker', 'outcome')
    op.drop_column('poc_tracker', 'stakeholder_signoff')
    op.drop_column('poc_tracker', 'failure_condition')
    op.drop_column('poc_tracker', 'target_date')
    op.drop_column('poc_tracker', 'success_metric')
    op.drop_column('poc_tracker', 'objective')
    op.drop_table('poc')
    # ### end Alembic commands ###
